# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Strykeforce
subtitle: A FIRST Robotics team
email: 
description: A FIRST Robotics team
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dev-sf-site.github.io" # the base hostname & protocol for your site
blog_url: "https://dev-sf-site.github.io/blog/"
author: Strykeforce
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# Logo settings
logo: ""
logo-image-url:
font-awesome-icon-logo:

# Social settings
github_username: 
twitter_username: 
google_username: 
instagram_username:
facebook_username: 
dribble_username:

github_url: https://github.com/strykeforce
twitter_url: 
facebook_url: 
instagram_url:
dribble_url:
google_url: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  #- jekyll-assets
host: 0.0.0.0

# Additional SEO Tag settings
social:
  name: Strykeforce
  links:
google_site_verification: 

#Jekyll Assets settings
assets:
  compress:
    css: true
    js: true
  cache: true
  prefix: "/assets"
  assets:
    - "*.png"
    - "*.pdf"
    - "*.jpg"
    - "*.jpeg"
  digest: true